id: P008261
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 13:11:49.017228
source_metadata:
  id: bdr:W25159
  title: དག་ཡིག་ཕྱོགས་བསྒྲིགས་མུ་ཏིག་ཚོམ་བུ།
  author: ''
  volumes:
    e42f2d80c9014e478682439dc479db0a:
      image_group_id: I4734
      title: ''
      volume_number: 1
      total_pages: 506
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
